name: Release

on:
  repository_dispatch:
    types: [rollingversions_publish_approved]
  push:
    branches:
      - master

permissions:
  id-token: write # Required for OIDC to publish to NPM
  contents: write # To create GitHub release

jobs:
  publish_canary:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 20.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npx rollingversions publish --canary $GITHUB_RUN_NUMBER --allow-any-branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' }}
    strategy:
      matrix:
        node-version: [20.x, 22.x, 24.x]
        # typescript-version: ['4.0.2']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install --frozen-lockfile
      # - run: yarn add -D typescript@${{ matrix.typescript-version }}
      - run: yarn build
      - run: yarn test

  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'repository_dispatch' }}
    needs: test
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org'
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: npx rollingversions publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
